---
title: JPE Replication Report
date: today
number-sections: true
format:
  html: default
---

# Paper Identification

|  |   |
| ---  |  -------|
| ID  |  {{< var paper_id >}} |
| Author  |  {{< var author >}} |
| Title  |  {{< var title >}} |
| Iteration |  {{< var round >}} |


Some useful information up front:

- [JPE Data and Code Availability Policy](https://www.journals.uchicago.edu/journals/jpe/datapolicy)
- [Step by step guidance from Data Editor for Authors](https://jpedataeditor.github.io/) 
- [Template README](https://social-science-data-editors.github.io/template_README/)




# Summary

In assessing compliance with our [Data and Code Availability Policy](https://www.journals.uchicago.edu/journals/jpe/datapolicy), our reproducibility team has identified the following issues, which we ask you to address:

1. Data Editor's first point.
2. Data Editor's second point.

# General

- [X] Data Availability and Provenance Statements
  - [X] Statement about Rights - Part 1: Right to use the data (e.g. *did the authors lawfully obtain the data*)
  - [X] Statement about Rights - Part 2: Right to publish the data (e.g. *are human subjects involved and did permission been granted to publish their data?*)
  - [X] License for Data (optional, but recommended)
  - [X] Details on each Data Source
- [X] Dataset list
- [X] Computational requirements
  - [X] Software Requirements
  - [X] Controlled Randomness (as necessary)
  - [X] Memory, Runtime, and Storage Requirements
- [X] Description of programs/code
  - [X] License for Code (Optional, but recommended) 
- [X] {REPLICATOR} to Replicators
  - [X] Details (as necessary)
- [X] List of tables and programs
- [X] References (Optional, but recommended) 


# High-level Description of Research Project

*This research project...*

- [X] uses observational data.
- [X] uses *confidential* observational data.
- [ ] uses data generated via experiment or trial by the authors (in field or lab).
  - [ ] For lab experiments: The code to implement the experimental protocol (z-Tree, o-Tree etc) is included in the package.
  - [ ] A PDF copy of IRB approval is contained in the package.
  - [ ] A PDF document outlining the design of the experiment, including information on the selection and eligibility of participants is included.
  - [ ] A PDF copy of the instructions given to participants in both original language and an English translation is included.
- [ ] uses data generated via survey by the authors (in field or online)
  - [ ] The programs used to administer the survey (e.g. qualtrics survey file) are included.
  - [ ] A PDF copy of IRB approval is contained in the package.
  - [ ] A PDF of the original questionaire(s) and information on the selection and eligibility of participants is included.
- [ ] is a simulation study: the data are generated by an algorithm.
- [ ] is a numerical illustration: no data are used but code is used to produce illustrative output (tables, figures)


# Data description

For any data that cannot be provided as part of the replication package, please provide the following information as part of the README.

> {REQUIRED}  Please specify how long the data will be preserved in the restricted-access location.

> {REQUIRED} Please provide affirmation of support for replication checks.
  - As per the [JPE policy](https://jpedataeditor.github.io/policy.html), "In cases where data cannot be published in an openly accessible trusted data repository like the JPE dataverse, authors who have requested an exemption to publish them at the time of first submission must commit to preserving the data and code for a period of no less than five years following the publication of the paper. They should also provide reasonable assistance to requests for clarification and replication."


> {REQUIRED} Please provide a codebook for the data.
  - The codebook should at a minimum describe the variables obtained from the data source, in a manner that will let others verify that they have obtained a substantially similar dataset if successfully obtaining access to the data.


## Data Sources

| file/name            | public | private | DOI/URL | Access described| cited readme | cited paper |
| ----                 | ---    | ---     | ---     | ---             | ----         | ----        | 
| suitability_resource/WDI_full.xlsx | yes    | no      | https://databank.worldbank.org/source/world-development-indicators (CC-BY 4.0)     | no              | yes          | yes         |
| patent_resource/g_patent.tsv | yes    | no      | https://patentsview.org/download/data-download-tables (CC-BY 4.0)     | yes              | yes          | yes         |
| patent_resource/g_us_patent_citation.tsv | yes    | no      | https://patentsview.org/download/data-download-tables (CC-BY 4.0)     | yes              | yes          | yes         |
| patent_resource/g_cpc_current.tsv | yes    | no      | https://patentsview.org/download/data-download-tables (CC-BY 4.0)     | yes              | yes          | yes         |
| patent_resource/g_application.tsv | yes    | no      | https://patentsview.org/download/data-download-tables (CC-BY 4.0)     | yes              | yes          | yes         |
| patent_resource/g_assignee_disambiguated.tsv | yes    | no      | https://patentsview.org/download/data-download-tables (CC-BY 4.0)     | yes              | yes          | yes         |
| patent_resource/g_location_disambiguated.tsv | yes    | no      | https://patentsview.org/download/data-download-tables (CC-BY 4.0)     | yes              | yes          | yes         |
| patent_resource/g_inventor_disambiguated.tsv | yes    | no      | https://patentsview.org/download/data-download-tables (CC-BY 4.0)     | yes              | yes          | yes         |
| geocoding_resource/ne_10m_admin_0_countries/ (shapefile set) | yes    | no      | https://www.naturalearthdata.com (Admin 0–Countries; Populated Places. 1:10m Cultural Vectors)     | no              | yes          | yes         |
| geocoding_resource/ne_10m_populated_places.{shp,dbf,shx,prj,cpg} | yes    | no      | https://www.naturalearthdata.com (Admin 0–Countries; Populated Places. 1:10m Cultural Vectors)     | no              | yes          | yes         |
| geocoding_resource/simplemaps.csv | yes    | no      | https://simplemaps.com/data/world-cities (CC-BY 4.0)     | no              | yes          | yes         |
| geocoding_resource/opendatasoft.csv | yes    | no      | https://public.opendatasoft.com/explore/dataset/geonames-all-cities-with-a- population-1000/ (CC-BY 4.0)     | no              | yes          | yes         |
| other_data_resource/un_polity_china.dta (+ twin) | yes    | no      |  https://doi.org/10.7910/DVN/LEJUQZ     | no              | yes          | yes         |
| other_data_resource/Trade_Volume_Export_I mport.csv | yes    | no      |  https://comtradeplus.un.org.     | no              | yes          | yes         |
| other_data_resource/table1_panelB_funding _sources.csv | yes    | no      |  Not provided     | no              | yes          | yes         |
| pitchbook/pbdeals.dta | no    | yes      |  Not provided     | yes              | yes          | yes         |
| pitchbook/pbcompanies.dta | no    | yes      |  Not provided     | yes              | yes          | yes         |
| pitchbook/pbinvestors.dta | no    | yes      |  Not provided     | yes              | yes          | yes         |
| pitchbook/pbdealinvestor.dta | no    | yes      |  Not provided     | yes              | yes          | yes         |
| pitchbook/pbmarketmap_v2.csv | no    | yes      |  Not provided     | yes              | yes          | yes         |
| pitchbook/pbdealinvestor.dta | no    | yes      |  Not provided     | yes              | yes          | yes         |
| pitchbook/later_years_extension/All_VC_Comp_Deal_Investor_2022-2024.csv | no    | yes      |  Not provided     | yes              | yes          | yes         |
| pitchbook/later_years_extension/pbmarketmap_22_24.csv | no    | yes      |  Not provided     | yes              | yes          | yes         |
| other_data_resource/LP.dta | no    | yes      |  Not provided     | yes              | yes          | yes         |

# Requirements 

- [X] README is in TXT, MD, or PDF format
- [X] README is accessible at the root of the package (not inside a folder)
- [X] Title conforms to guidance (starts with "Data and Code for: Title of Paper" or "Code for: Title of Paper", is properly capitalized)
- [X] Authors (with affiliations) are listed in the same order as on the paper


## Stated Requirements

- [ ] No requirements specified
- [X] Software Requirements specified as follows:
  - Stata 19.5
  - Python >= 3.11
- [X] Computational Requirements specified as follows:
  - At least 64gb of memory, parallel computing capabilities.
- [X] Time Requirements specified as follows:
  - If parallel computing: ~8-10 hours. If not, could be up to 48 hours.

- [X] Requirements are complete.

# Analyzing Data and Code Files


{{< include generated/report-pii.md >}}

{{< include generated/report-file-paths.md >}}

{{< include generated/report-duplicates.md >}}

{{< include generated/report-zero-files.md >}}

{{< include generated/report-large-files.md >}}



## Code description

- Stage A prepares data.
- Each sub script in stage B generates one exhibit.

{{< include generated/report-cloc.md >}}


- [X] The replication package contains a "main" or "master" file(s) which calls all other auxiliary programs.

> NOTE: In-text numbers that reference numbers in tables do not need to be listed. Only in-text numbers that correspond to no table or figure need to be listed.

## Computing Environment of the Replicator

- Onyxia `RStudio` instance with 25000m CPU allocation and 124 Gb of memory, 100Gb of persistent storage. Custom Docker image ([see here](https://hub.docker.com/repository/docker/prantoine/stata19_5-mp)) based on `dataeditors/stata19_5-mp`
- Running Debian 6.12.86-1 on `Intel(R) Xeon(R) Gold 6448Y` with 32 cores.

- Stata/MP 19.5
- Pyton 3.12 in a clean virtual environment

# Replication

- Downloaded code and data from dropbox.
- Commited code to git repo.
- Used a custom `stata19_5-mp` Docker image to run on the instance.
- Installed python's `venv` package and activated a new virtual environment at the root of the filesystem in Onyxia service (as per `README` recommendations)
- Ran `code/run_all.sh`
- Stage A produces one error, `9`:
```bash
>>> stata:  code/generate/09_generate_simulated_deals.do
    ERROR: code/generate/09_generate_simulated_deals.do hit a Stata error r(693); - see output/logs/generate/09_generate_simulated_deals.log
```
Logs show that this is due to lack of space on device.

- Some steps in Stage B did not succeed:

  - One stage B step was skipped:

```bash
>>> SKIPPED: code/tables/table_A8.do
    missing input: confidential-data-not-for-publication/Analysis/intermediate_and_other_data/simulated_deals_all_1_500.dta
    TABLE A8 requires Stage-A step 09 (the Monte-Carlo simulation, skipped under --skip-heavy): bash code/generate/09_generate_simulated_deals.sh 7
```
  - Two stage B steps failed:

```bash
>>> stata:  code/figures/figure_A14.do
    ERROR: code/figures/figure_A14.do hit a Stata error r(601); - see output/logs/figure_A14.log
>>> stata:  code/figures/figure_A15.do
    ERROR: code/figures/figure_A15.do hit a Stata error r(601); - see output/logs/figure_A15.log
```
- Due to missing package `gtools` which was supposed to be installed in the package installation script. The package could be installed with `ssc install gtools`.

- All other exhibits were generated.

# Findings {#sec-findings}

## Data Preparation Code

## Tables and Figures


| Data Preparation Program      | Dataset created                                    | Reproduced? |              |
|-------------------------------|----------------------------------------------------|-------------|--------------|
| Files in code/BERT_generation | 9 files in BERT_prediction_resource/ (+ CSV twins) | Yes         |              |
| Figure/Table #                | Program                                            | Line Number | Reproduced?  |
| Table 1                       | code/tables/table_1.py                             | -           | Yes          |
| Table 2                       | code/tables/table_2.do                             | -           | Yes          |
| Table 3                       | code/tables/table_3.do                             | -           | Yes          |
| Table 4                       | code/tables/table_4.do                             | -           | Yes          |
| Table 5                       | code/tables/table_5.do                             | -           | Yes          |
| Table 6                       | code/tables/table_6.do                             | -           | Yes          |
| Table 7                       | code/tables/table_7.do                             | -           | Yes          |
| Table 8                       | code/tables/table_8.do                             | -           | Yes          |
| Table A1                      | code/tables/table_A1.py                            | -           | Yes          |
| Tabe A3                       | No script (textual data)                           | -           | -            |
| Table A2                      | code/tables/table_A2.do                            | -           | Yes          |
| Table A4                      | code/tables/table_A4.do                            | -           | Yes          |
| Table A5                      | code/tables/table_A5.do                            | -           | Yes          |
| Table A6                      | code/tables/table_A6.do                            | -           | Yes          |
| Table A7                      | code/tables/table_A7.do                            | -           | Yes          |
| Table A8                      | code/tables/table_A8.do                            | -           | No (**NEEDS STEP 09**)          |
| Table A9                      | code/tables/table_A9.do                            | -           | Yes          |
| Table A10                     | code/tables/table_A10.do                           | -           | Yes          |
| Table A11                     | code/tables/table_A11.do                           | -           | Yes          |
| Table A12                     | code/tables/table_A12.do                           | -           | Yes          |
| Table A13                     | code/tables/table_A13.do                           | -           | Yes          |
| Table A14                     | code/tables/table_A14.do                           | -           | Yes          |
| Table A15                     | code/tables/table_A15.do                           | -           | Yes          |
| Table A16                     | code/tables/table_A16.do                           | -           | Yes          |
| Table A17                     | code/tables/table_A17.do                           | -           | Yes          |
| Table A18                     | code/tables/table_A18.do                           | -           | Yes          |
| Table A19                     | No script (textual data)                           | -           | -            |
| Table A20                     | code/tables/table_A20.do                           | -           | Yes          |
| Table A21                     | code/tables/table_A21.do                           | -           | Yes          |
| Table A22                     | code/tables/table_A22.do                           | -           | Yes          |
| Table A23                     | code/tables/table_A23.do                           | -           | Yes          |
| Table A24                     | code/tables/table_A24.do                           | -           | Yes          |
| Table A25                     | code/tables/table_A25.do                           | -           | Yes          |
| Table A26                     | code/tables/table_A26.do                           | -           | Yes          |
| Table A27                     | code/tables/table_A27.do                           | -           | Yes          |
| Table A28                     | code/tables/table_A28.do                           | -           | Yes          |
| Table A29                     | code/tables/table_A29.do                           | -           | Yes          |
| Table A30                     | code/tables/table_A30.do                           | -           | Yes          |
| Figure 1                      | code/figures/figure_1.py                           | -           | Yes          |
| Figure 2                      | code/figures/figure_2.do                           | -           | Yes          |
| Figure 3                      | code/figures/figure_3.do                           | -           | Yes          |
| Figure 4                      | code/figures/figure_4.do                           | -           | Yes          |
| Figure A1                     | code/figures/figure_A1.do                          | -           | Yes          |
| Figure A2                     | code/figures/figure_A2.do                          | -           | Yes          |
| Figure A3                     | code/figures/figure_A3.do                          | -           | Yes          |
| Figure A4                     | code/figures/figure_A4.do                          | -           | Yes          |
| Figure A5                     | code/figures/figure_A5.do                          | -           | Yes          |
| Figure A6                     | code/figures/figure_A6.do                          | -           | Yes          |
| Figure A7                     | code/figures/figure_A7.do                          | -           | Yes          |
| Figure A8                     | code/figures/figure_A8.do                          | -           | Yes |
| Figure A9                     | code/figures/figure_A9.do                          | -           | Yes           |
| Figure A10                    | code/figures/figure_A10.do                         | -           | Yes          |
| Figure A11                    | code/figures/figure_A11.do                         | -           | No (skipped **TEMPORARY: NEEDS STEP 08B**, can be run independently now) |
| Figure A12                    | code/figures/figure_A12.do                         | -           | Yes          |
| Figure A13                    | code/figures/figure_A13.do                         | -           | Yes          |
| Figure A14                    | code/figures/figure_A14.do                         | -           | No (skipped) |
| Figure A15                    | code/figures/figure_A15.do                         | -           | No (skipped) |
| Figure A16                    | code/figures/figure_A16.do                         | -           | Yes          |
| Figure A17                    | code/figures/figure_A17.do                         | -           | Yes          |
| In-text numbers               | Program                                            | Line Number |              |

- Two figures (A14 and A14) were not generated, but the scripts did not show any errors. 
- The other exhibits not generated (Figures A8 and A11) were logged as skipped (in stage A).
- One error reported for figure A9 (in stage B).

## In-Text Numbers

- [ ] In-text numbers not verified.

- [X] There are no in-text numbers, or all in-text numbers stem from tables and figures.

- [ ] There are in-text numbers, but they are not identified in the code

## Other Issues

# Classification

- [ ] full reproduction
- [ ] full reproduction with minor issues
- [X] partial reproduction (see above)
- [ ] not able to reproduce most or all of the results (reasons see above)

## Reason for incomplete reproducibility

- [ ] None.
- [ ] `Discrepancy in output` (either figures or numbers in tables or text differ)
- [ ] `Bugs in code` that were fixable by the replicator (but should be fixed in the final deposit)
- [ ] `Code missing`, in particular if it prevented the replicator from completing the reproducibility check
  - [ ] `Data preparation code missing` should be checked if the code missing seems to be data preparation code
- [X] `Code not functional` is more severe than a simple bug: it prevented the replicator from completing the reproducibility check
- [ ] `Software not available to replicator` may happen for a variety of reasons, but in particular (a) when the software is commercial, and the replicator does not have access to a licensed copy, or (b) the software is open-source, but a specific version required to conduct the reproducibility check is not available.
- [ ] `Insufficient time available to replicator` is applicable when (a) running the code would take weeks or more (b) running the code might take less time if sufficient compute resources were to be brought to bear, but no such resources can be accessed in a timely fashion (c) the replication package is very complex, and following all (manual and scripted) steps would take too long.
- [X] `Data missing` is marked when data *should* be available, but was erroneously not provided, or is not accessible via the procedures described in the replication package
- [ ] `Data not available` is marked when data requires additional access steps, for instance purchase or application procedure. 
- [ ] `Missing README` is marked if there is no README to guide the replicator, or the README is not in compliance with JPE requirements


{{< include generated/report-pii.md >}}